# ### DATA ###

Muon_Run2023C:
  era: '2023'
  type: data
  group: data
  db: [das:/Muon0/Run2023C-22Sep2023_v1-v1/NANOAOD, das:/Muon0/Run2023C-22Sep2023_v2-v1/NANOAOD, das:/Muon0/Run2023C-22Sep2023_v3-v1/NANOAOD, das:/Muon0/Run2023C-22Sep2023_v4-v1/NANOAOD, das:/Muon1/Run2023C-22Sep2023_v1-v1/NANOAOD, das:/Muon1/Run2023C-22Sep2023_v2-v1/NANOAOD, das:/Muon1/Run2023C-22Sep2023_v3-v1/NANOAOD, das:/Muon1/Run2023C-22Sep2023_v4-v2/NANOAOD]
  run_range: &runs_23C [367765, 369802]
  certified_lumi_file: &lumi_cert_23 https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions23/Cert_Collisions2023_366442_370790_Golden.json
  split: &nsplit -1

Muon_Run2023D:
  era: '2023BPix'
  type: data
  group: data
  db: [das:/Muon0/Run2023D-22Sep2023_v1-v1/NANOAOD, das:/Muon0/Run2023D-22Sep2023_v2-v1/NANOAOD, das:/Muon1/Run2023D-22Sep2023_v1-v1/NANOAOD, das:/Muon1/Run2023D-22Sep2023_v2-v1/NANOAOD]
  run_range: &runs_23D [370603, 372415]
  certified_lumi_file: *lumi_cert_23
  split: *nsplit

EGamma_Run2023C:
  era: '2023'
  type: data
  group: data
  db: [das:/EGamma0/Run2023C-22Sep2023_v1-v1/NANOAOD, das:/EGamma0/Run2023C-22Sep2023_v2-v1/NANOAOD, das:/EGamma0/Run2023C-22Sep2023_v3-v1/NANOAOD, das:/EGamma0/Run2023C-22Sep2023_v4-v1/NANOAOD, das:/EGamma1/Run2023C-22Sep2023_v1-v1/NANOAOD, das:/EGamma1/Run2023C-22Sep2023_v2-v1/NANOAOD, das:/EGamma1/Run2023C-22Sep2023_v3-v1/NANOAOD, das:/EGamma1/Run2023C-22Sep2023_v4-v1/NANOAOD]
  run_range: *runs_23C
  certified_lumi_file: *lumi_cert_23
  split: *nsplit

EGamma_Run2023D:
  era: '2023BPix'
  type: data
  group: data
  db: [das:/EGamma0/Run2023D-22Sep2023_v1-v1/NANOAOD, das:/EGamma0/Run2023D-22Sep2023_v2-v1/NANOAOD, das:/EGamma1/Run2023D-22Sep2023_v1-v1/NANOAOD, das:/EGamma1/Run2023D-22Sep2023_v2-v1/NANOAOD]
  run_range: *runs_23D
  certified_lumi_file: *lumi_cert_23
  split: *nsplit

MuonEG_Run2023C:
  era: '2023'
  type: data
  group: data
  db: [das:/MuonEG/Run2023C-22Sep2023_v1-v1/NANOAOD, das:/MuonEG/Run2023C-22Sep2023_v2-v1/NANOAOD, das:/MuonEG/Run2023C-22Sep2023_v3-v1/NANOAOD, das:/MuonEG/Run2023C-22Sep2023_v4-v1/NANOAOD]
  run_range: *runs_23C
  certified_lumi_file: *lumi_cert_23
  split: *nsplit

MuonEG_Run2023D:
  era: '2023BPix'
  type: data
  group: data
  db: [das:/MuonEG/Run2023D-22Sep2023_v1-v1/NANOAOD, das:/MuonEG/Run2023D-22Sep2023_v2-v1/NANOAOD]
  run_range: *runs_23D
  certified_lumi_file: *lumi_cert_23
  split: *nsplit

# ## MC ###

TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023:
  era: '2023'
  db: das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: "TTbar"
  cross-section: 98.036113
  generated-events: genEventSumw
  split: *nsplit

TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023BPix:
  era: '2023BPix'
  db: das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
  type: mc
  group: "TTbar"
  cross-section: 98.036113
  generated-events: genEventSumw
  split: *nsplit

# TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8:
#   dbs:
#     2022:
#       [
#         das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
#         das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
#       ]
#     2022EE:
#       [
#         das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
#         # das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
#       ]
#   type: mc
#   group: "TTbar"
#   cross-section: 405.74553
#   generated-events: genEventSumw
#   split: *nsplit

DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023:
  era: '2023'
  db: das:/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v1/NANOAODSIM
  type: mc
  group: "DY"
  cross-section: 6.735e+03
  generated-events: genEventSumw
  split: *nsplit

DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023BPix:
  era: '2023BPix'
  db: das:/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
  type: mc
  group: "DY"
  cross-section: 6.735e+03
  generated-events: genEventSumw
  split: *nsplit

# DYto2L-2Jets_MLL-50_0J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022:
#   era: '2022'
#   db: das:/DYto2L-2Jets_MLL-50_0J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
#   type: mc
#   group: "DY"
#   cross-section: 5.401e+03
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-50_0J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022EE:
#   era: '2022EE'
#   db: das:/DYto2L-2Jets_MLL-50_0J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM # 452 files
#   type: mc
#   group: "DY"
#   cross-section: 5.401e+03
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-50_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022:
#   era: '2022'
#   db: das:/DYto2L-2Jets_MLL-50_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM # 196 files
#   type: mc
#   group: "DY"
#   cross-section: 1.005e+03
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-50_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022EE:
#   era: '2022EE'
#   db: das:/DYto2L-2Jets_MLL-50_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM # 454 files
#   type: mc
#   group: "DY"
#   cross-section: 1.005e+03
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-50_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022:
#   era: '2022'
#   db: das:/DYto2L-2Jets_MLL-50_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM # 177 files
#   type: mc
#   group: "DY"
#   cross-section: 3.845e+02
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-50_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2022EE:
#   era: '2022EE'
#   db: das:/DYto2L-2Jets_MLL-50_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM # 386 files
#   type: mc
#   group: "DY"
#   cross-section: 3.845e+02
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023:
#   era: '2023'
#   db: das:/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14_ext1-v3/NANOAODSIM
#   type: mc
#   group: "DY"
#   cross-section: 19982.5
#   generated-events: genEventSumw
#   split: *nsplit

# DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023BPix:
#   era: '2023BPix'
#   db: das:/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2_ext1-v3/NANOAODSIM
#   type: mc
#   group: "DY"
#   cross-section: 19982.5
#   generated-events: genEventSumw
#   split: *nsplit

WW_TuneCP5_13p6TeV_pythia8_2023:
  era: '2023'
  db: das:/WW_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 80.18
  generated-events: genEventSumw
  split: &nsplit -1

WW_TuneCP5_13p6TeV_pythia8_2023BPix:
  era: '2023BPix'
  db: das:/WW_TuneCP5_13p6TeV_pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 80.18
  generated-events: genEventSumw
  split: *nsplit

WZ_TuneCP5_13p6TeV_pythia8_2023:
  era: '2023'
  db: das:/WZ_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 29.1
  generated-events: genEventSumw
  split: *nsplit

WZ_TuneCP5_13p6TeV_pythia8_2023BPix:
  era: '2023BPix'
  db: das:/WZ_TuneCP5_13p6TeV_pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 29.1
  generated-events: genEventSumw
  split: *nsplit

WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023:
  era: '2023'
  db: das:/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v15-v2/NANOAODSIM
  type: mc
  group: "WJets"
  cross-section: 5.557e+04
  generated-events: genEventSumw
  split: *nsplit

WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_2023BPix:
  era: '2023BPix'
  db: das:/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v6-v2/NANOAODSIM
  type: mc
  group: "WJets"
  cross-section: 5.557e+04
  generated-events: genEventSumw
  split: *nsplit

ZZ_TuneCP5_13p6TeV_pythia8_2023:
  era: '2023'
  db: das:/ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 12.75
  generated-events: genEventSumw
  split: *nsplit

ZZ_TuneCP5_13p6TeV_pythia8_2023BPix:
  era: '2023BPix'
  db: das:/ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 12.75
  generated-events: genEventSumw
  split: *nsplit

# TW cross section from: https://cms-talk.web.cern.ch/t/new-jecs-for-run3-prompt-fg-eras/26529
TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023:
  era: '2023'
  db: das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v15-v4/NANOAODSIM
  type: mc
  group: "TW"
  cross-section: 4.6651009 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu)^2 x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259^2 x 2
  generated-events: genEventSumw
  split: *nsplit

TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023BPix:
  era: '2023BPix'
  db: das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v6-v2/NANOAODSIM
  type: mc
  group: "TW"
  cross-section: 4.6651009 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu)^2 x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259^2 x 2
  generated-events: genEventSumw
  split: *nsplit

# TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8:
#   era: '2023'
#   db: [
#         das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
#         # das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
#       ]
#   type: mc
#   group: "TW"
#   cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741
#   generated-events: genEventSumw
#   split: *nsplit

# TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8EE:
#   era: '2022EE'
#   db: [
#         das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
#         # das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
#       ]
#   type: mc
#   group: "TW"
#   cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741
#   generated-events: genEventSumw
#   split: *nsplit

TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023:
  era: '2023'
  db: das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: "TW"
  cross-section: 4.6651009
  generated-events: genEventSumw
  split: *nsplit

TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_2023BPix:
  era: '2023BPix'
  db: das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
  type: mc
  group: "TW"
  cross-section: 4.6651009
  generated-events: genEventSumw
  split: *nsplit

# TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_2022:
#   era: '2023'
#   db: [
#         das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
#         # das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
#       ]
#   type: mc
#   group: "TW"
#   cross-section: 19.307618
#   generated-events: genEventSumw
#   split: *nsplit

# TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_2022EE:
#   era: '2023'
#   db: [
#         das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
#         # das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
#       ]
#   type: mc
#   group: "TW"
#   cross-section: 19.307618
#   generated-events: genEventSumw
#   split: *nsplit

# ## SIGNAL ###
# GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00:
#   type: signal
#   dbs:
#     '2023': das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
#     2022EE: das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v3/NANOAODSIM
#   cross-section: 0.02964 # value from xsdb, BR may be needed
#   branching-ratio: 0.21962178
#   generated-events: genEventSumw
#   split: -25
#   line-color: 3
#   legend: 'HHto2B2WtoLNu2Q'

# GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_2022:
#   type: signal
#   era: '2023'
#   db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v1/NANOAODSIM
#   cross-section: 0.03413
#   branching-ratio: 0.10614564 # BR(W->LNu)^2=(3*10.86/100)^2
#   generated-events: genEventSumw
#   split: -25
#   line-color: 3
#   legend: 'HH\rightarrow bbll\nu\nu'

# GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_2022EE:
#   type: signal
#   era: '2022EE'
#   db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
#   cross-section: 0.03413
#   branching-ratio: 0.10614564 # BR(W->LNu)^2=(3*10.86/100)^2
#   generated-events: genEventSumw
#   split: -25
#   line-color: 3
#   legend: 'HH\rightarrow bbll\nu\nu'

# ### BSM ###
# GluGlutoHHto2B2WtoLNu2Q_kl-2p45_kt-1p00_c2-0p00:
#   type: signal
#   dbs:
#     '2023': das:/GluGluToHHTo2B2VTo2L2Nu_node_cHHH2p45_TuneCP5_PSWeights_13TeV-powheg-pythia8/RunIIFall17NanoAODv7-PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/NANOAODSIM
#     2022EE: das:/GluGluToHHTo2B2VTo2L2Nu_node_cHHH2p45_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM
#   cross-section: 0.013124
#   branching-ratio: 0.027669886574221
#   generated-events: genEventSumw
#   split: -10
#   # line-color: '#FFFFFF'
#   # legend: 'HHto2B2WtoLNu2Q'

# GluGlutoHHto2B2Vto2L2Nu_kl-5p00_kt-1p00_c2-0p00:
#   type: signal
#   dbs:
#     '2023': das:/GluGluToHHTo2B2VTo2L2Nu_node_cHHH5_TuneCP5_PSWeights_13TeV-powheg-pythia8/RunIIFall17NanoAODv7-PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/NANOAODSIM
#     2022EE: das:/GluGluToHHTo2B2VTo2L2Nu_node_cHHH5_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM
#   cross-section: 0.091172
#   branching-ratio: 0.027669886574221
#   generated-events: genEventSumw
#   split: -10
#   line-color: 3
#   legend: 'HH\rightarrow bbll\nu\nu'
